### ISSUE TITLE
[FEATURE] - Message Appears when trying to save read only file

### ISSUE THREAD

**Issue by trymeouteh** [alefragnani/vscode-read-only-indicator#68]
Please add a feature which will have a messagebox appears when you try to save the file to inform the user that the file is a read-only file and it cannot be saved.

**Comment by alefragnani** [comment]
Hi @trymeouteh ,

I'm not sure you are aware of, but VS Code itself already does that. But it displays a Notification (at the bottom-right corner of the window) instead of a MessageBox. 

I suppose you could ask them to change how this message is displayed, using a MessageBox instead, which is IMHO, way better than a Notification for this scenario.

Hope this helps
