### ISSUE TITLE
No Changelog in VS Code extension display

### ISSUE THREAD

**Issue by BillDenton** [alefragnani/vscode-read-only-indicator#7]
Shows "No Changelog available" in VS Code. Instead change log appears at bottom of details. Details of how to do this may be in https://github.com/Jason-Rev/vscode-spell-checker/issues/50

**Comment by alefragnani** [comment]
Well, they should have closed [my issue](https://github.com/Microsoft/vscode/issues/4090), so I would know that `CHANGELOG.md` is now supported 😄 

Besides, the [manifest documentation](http://code.visualstudio.com/docs/extensionAPI/extension-manifest) still doesn't say anything about changelog support.

I will have take a look about the _supported way_, because there a lot of issues related to this, even some saying about _stability_.

**Comment by BillDenton** [comment]
Checked looks good.
