### ISSUE TITLE
Feature request: "Make file executable" menu option

### ISSUE THREAD

**Issue by darkvertex** [alefragnani/vscode-read-only-indicator#8]
Maybe it's not the business of a "ReadOnly Indicator" extension to be doing this, but since you already have "Make file read only" and "Make file writable" menu options, could we have a "Make file executable" (for Linux/OSX users, in Windows I guess everything is executable.)

More than once I'm starting a bash script or a standalone Python script with a shebang line and I forget to make it executable until later, but it'd be so easy if I could do it from the menu right away without having to spawn a terminal!

**Comment by alefragnani** [comment]
Hi @darkvertex ,

I don't know if you did check the commands, but it does not support MacOS or Linux, today 😢 . 

The main reason is that MacOS and Linux works differently (from Windows) in this area, and since I didn't have access to a MacOS/Linux computer, I decided to not support them.

But even this being _a bit off limits_ for this extension purposes, I don't see any problem to add a new command, specially for `Make File Executable` for MacOS/Linux. I just have to have access to some of this OS.

Thanks for your suggestion

**Comment by alefragnani** [comment]
I'm closing this feature request because it didn’t receive enough upvotes from the community. Still a big Thank You to you for taking the time to create this issue!

Thanks for your understanding
