### ISSUE TITLE
[FEATURE] Tab Color Change

### ISSUE THREAD

**Issue by trobinson794** [alefragnani/vscode-read-only-indicator#88]
It would be nice if there was a better indication of when a file was set to Read Only like changing of the tab color.  I noticed there are extensions to change tab colors so it should be possible.  Thanks.

**Comment by alefragnani** [comment]
Hi @trobinson794 ,

I'm not sure which extension you are referring to, but I don't know of any API or color customizations that would allow this kind of change. 

Looking at the marketplace, I found this extension, https://marketplace.visualstudio.com/items?itemName=mondersky.tabscolor, which seems to _patch_ VS Code installation, in order to provide that feature. If that's the extension you are referring to, I'm sorry to say, but I wouldn't add this feature to the extension. 

Otherwise, please provide the name of the extension that you tested, so I could take a look

Hope this helps

**Comment by trobinson794** [comment]
You are correct, I think that is the one I saw.  I guess if they had to patch it, then that's not an API feature.   Thanks for looking into this.  I'll make a suggestion that they add that API feature.   Probably won't happen but it's worth a shot.

**Comment by alefragnani** [comment]
Thanks for follow up. 
Hope they can provide the feature for you. Good luck.
